name: Backend CI

on:
  push:
    branches:
      - main
      - gh-actions-workflows # test
  pull_request:
    branches:
      - main
      - gh-actions-workflows # test

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.9

    - name: Install dependencies
      run: |
        npm install

    - name: Build TypeScript
      run: |
        npm run build

    - name: Run Backend Tests
      run: |
        cd Backend
        npm run test
