name: Build and Push to Dockerhub

on:
  push:
    branches: [ main, deployment ]
  pull_request:
    branches: [ main, deployment ]

env:
  USERNAME: justingebert
  IMAGE_NAME: hypnobuddy-backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine tag
        id: prep
        run: |
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            echo ::set-output name=tag::pr-${{ github.event.number }}
          else
            echo ::set-output name=tag::latest
          fi
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.tag }}
