name: Build and Push to Dockerhub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  USERNAME: justingebert
  IMAGE_NAME: hypnobuddy-backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest