name: 'Terraform Plan'

on:
  pull_request:
    branches: [ main, deployment ]

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./Backend/terraform

      - name: 'Terraform Plan'
        run: terraform plan -no-color | tee plan_output.txt
        working-directory: ./Backend/terraform
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: 'List files in Terraform directory'
        run: ls -l ./Backend/terraform
        working-directory: ./Backend/terraform

      - name: Comment Terraform Plan on PR
        uses: blinqas/tf-plan-pr-comment@v1.1.0
        with:
          output_file: './Backend/terraform/plan_output.txt'
          headline: '### Terraform Plan Output'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
