name: 'Terraform Apply'

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./Backend/terraform

      - name: 'Terraform Delete (this should be removed later -> get last tag from docker gh action)'
        run: terraform destroy -auto-approve
        working-directory: ./Backend/terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: ./Backend/terraform
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}
