name: 'Terraform Apply'

on:
  push:
    branches: [ main, deployment ]

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}
